### ISSUE TITLE
Clarification of StartTimeUnixNano in metrics proto

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-proto#229] opened 2020-10-28 20:55 UTC
The documentation around StartTimeUnixNano is a bit unclear because it says it MUST be set to the start of an interval:

> // - StartTimeUnixNano MUST be set to the start of the interval when the data's
> //   type includes an AggregationTemporality. This field is not set otherwise.

[Source
](https://github.com/open-telemetry/opentelemetry-proto/blob/59c488bfb8fb6d0458ad6425758b70259ff4a2bd/opentelemetry/proto/metrics/v1/metrics.proto#L99)

Then later it says 0 means it's unspecified.

>   // Value of 0 indicates that the timestamp is unspecified. In that case the
>   // timestamp may be decided by the backend.

[Source](https://github.com/open-telemetry/opentelemetry-proto/blob/59c488bfb8fb6d0458ad6425758b70259ff4a2bd/opentelemetry/proto/metrics/v1/metrics.proto#L307)

These seem a bit conflicting since I don't think an unspecified interval can be considered the start of an interval.

Also it's unclear what should be done when StartTimeUnixNano is unknown for a cumulative metric. Imagine that you are scraping an Apache status endpoint for "total_bytes_received" but you are unable to determine the start time of the server (when the metric was 0). What should StartTimeUnixNano be set to? (Perhaps depends on the outcome of the above issue.)

@bogdandrutu @jmacd

**Comment by jkwatson** [comment] 2020-10-28 21:40
It seems like if you're scraping a cumulative metric, you should be recording that data as a SumObserver, which should use the LastValue aggregation, and end up as a Gauge-type metric in OTLP, which doesn't require a time range, IIRC.

**Comment by jrcamp** [comment] 2020-10-29 15:09
> It seems like if you're scraping a cumulative metric, you should be recording that data via a SumObserver, which should use the LastValue aggregation, and end up as a Gauge-type metric in OTLP, which doesn't require a time range, IIRC.

Looks like SumObserver ends up as Sum in OTLP. See [this comment](https://github.com/open-telemetry/opentelemetry-proto/blob/59c488bfb8fb6d0458ad6425758b70259ff4a2bd/opentelemetry/proto/metrics/v1/metrics.proto#L135).

**Comment by jkwatson** [comment] 2020-10-29 15:32
> > It seems like if you're scraping a cumulative metric, you should be recording that data via a SumObserver, which should use the LastValue aggregation, and end up as a Gauge-type metric in OTLP, which doesn't require a time range, IIRC.
> 
> Looks like SumObserver ends up as Sum in OTLP. See [this comment](https://github.com/open-telemetry/opentelemetry-proto/blob/59c488bfb8fb6d0458ad6425758b70259ff4a2bd/opentelemetry/proto/metrics/v1/metrics.proto#L135).

Hm. Well, if you don't have a start time, then you probably need to make it a ValueObserver, which does report as a gauge. It's a shame we lose a little bit of information in this approach (namely, that it's monotonic).

**Comment by jmacd** [comment] 2021-03-15 22:21
https://github.com/lightstep/opentelemetry-prometheus-sidecar takes an approach inherited from https://github.com/Stackdriver/stackdriver-prometheus-sidecar on this topic, which I've begun to think of as a cumulative-to-delta-to-cumulative transform. The idea is to leave a gap in the series at the point where a cumulative of unknown-reset-time appears, a point of transition where the actual rate of the series is unknown. The cumulative value first reported then becomes the reset value of the series, after which successive values are correctly timestamped cumulative / monotonic data points.

The gap in the series serves is reflected in one lost point, the reset value. In that gap, for all we know, any number of true resets may have taken place.  Prometheus has similar ambiguity around resets, where instead of the gap proposed here, the value is presumed to have reset once any time the value falls from the previous known value in the series. https://github.com/lightstep/opentelemetry-prometheus-sidecar/blob/13e3b89cd20909a1dcc98d20e6fe1afdc437482a/retrieval/series_cache.go#L273

**Comment by jmacd** [comment] 2021-04-06 16:44
This is a duplicate of #292

**Closed by jmacd** 2021-04-06 16:44 UTC
Labels: area:data-model, priority:p2, release:allowed-for-ga, spec:metrics
