### ISSUE TITLE
Helper enums ZERO value is incorrectly used

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-proto#433] opened 2022-10-18 01:23 UTC
In the collector before we removed access to the helper enums like `DataPointFlags` (https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L321), I've seen code comparing with `FLAG_NONE` or initializing as `FLAG_NONE` the value of the flags to check if a value is present. 

If the helper enums contain "masks" then ZERO value does not make sense, if the enums contain "absolute" values, then zero value makes sense but the other values don't make sense.

My personal suggestion is still to remove them (see https://github.com/open-telemetry/opentelemetry-proto/pull/423) but if that is not ok, this inconsistency between masks/absolute value has to be fixed.

Assigning to @tigrannajaryan since he is a big supported of these values.

**Comment by tigrannajaryan** [comment] 2022-10-18 12:43
>If the helper enums contain "masks" then ZERO value does not make sense

@bogdandrutu I think you are right. I support removing the zero value from enums for bitmasks.

**Comment by tigrannajaryan** [comment] 2022-10-18 15:21
I think this should be done before 1.0 so adding to the milestone.

**Comment by Aneurysm9** [comment] 2022-10-18 21:43
I'm not sure what the problem is with the way things are currently.  If a helper enum contains bitmask values then a `NONE` value still makes sense.

```go
const (
	FLAG_NONE = 0
	FLAG_RED = 1
	FLAG_BLUE = 2
	FLAG_GREEN = 4
)

// 7
value := FLAG_NONE | FLAG_RED | FLAG_BLUE | FLAG_GREEN

// false
isNone := value == FLAG_NONE // or, value == value & FLAG_NONE

// true
isRed := FLAG_RED == value & FLAG_RED

//true
isGreen := FLAG_GREEN == value & FLAG_GREEN

//true
isBlue := FLAG_BLUE == value & FLAG_BLUE
```

While it can allow for nonsensical combinations, this is likely the case for many bitmask-type flag sets and there are still sensible ways to interact with them.  Is a user required to utilize the values correctly? Yes.  That's the case regardless whether we include helper enums or not, though.  

Are there concrete examples of these values being used incorrectly that can be pointed out?  I think in their absence it will be difficult to progress here.

**Comment by bogdandrutu** [comment] 2022-10-18 23:47
What is the meaning of "None" in a bit map? Why do you not offer a "All" (or other subset)?

**Comment by tigrannajaryan** [comment] 2022-10-19 14:20
I think the check `bitmask_field == FLAG_NONE` is often used as a proxy for `(bitmask_field & FLAG_RED == 0) && (bitmask_field & FLAG_GREEN == 0) && (bitmask_field & FLAG_BLUE = 0)`.

It is an incorrect usage because `bitmask_field` typically contains reserved bits which can be allocated in the future and these two checks will no longer have the same meaning.

**Comment by tigrannajaryan** [comment] 2023-04-28 17:00
I looked into this and unfortunately am unable to fix it.

Protobufs [require that enums start with a 0 value](https://protobuf.dev/programming-guides/proto3/#enum).

If you try to omit it you get a compilation error:
```
opentelemetry/proto/metrics/v1/metrics.proto:325:28: The first enum value must be zero in proto3.
```

Alternatively, trying to use a dummy name, e.g.:
```
enum DataPointFlags {
  _ = 0;
 FLAG_NO_RECORDED_VALUE = 1;
}
```

Fails Objective-C generator:
```
error: got empty string for making TextFormat data, input: "", desired: "_".
```

Also tried declaring it reserved as the doc says should be possible:
```
enum DataPointFlags {
  reserved 0;
  FLAG_NO_RECORDED_VALUE = 1;
}
```

but get an error again:
```
opentelemetry/proto/metrics/v1/metrics.proto:327:28: The first enum value must be zero in proto3.
```

If anyone knows how to fix this please let me know, otherwise I am going to close this issue.

**Comment by tigrannajaryan** [comment] 2023-04-28 17:01
@open-telemetry/specs-approvers If anyone knows how to fix this please let me know, otherwise I am going to close this issue (see comment above).

**Comment by jmacd** [comment] 2023-05-02 15:18
I feel we are going too far. Let's just let there be a FLAG_NONE and carefully document that it is a bitmask value.

**Comment by yurishkuro** [comment] 2023-05-10 17:38
As others have pointed out, I am not really seeing why `mask == NONE` is incorrect as a general statement. 
* In some cases the mask represents a grouping of unrelated things (e.g. the Flags field in Traceparent has bits for is_sampled and is_id_random). In those scenarios asking a question `mask == 0` has no semantic meaning imo.
* But in other cases bitmasks are used as a quick check for set members, e.g. you have a group of callbacks / handlers for a given instrumentation point and you want to control via configuration which handlers are allowed in a given locus. In this scenario the question `mask == 0` makes total sense as you can short circuit the whole loop, and it is completely reasonable to write the question as `mask == NONE`.

**Comment by tigrannajaryan** [comment] 2023-05-10 18:55
> As others have pointed out, I am not really seeing why `mask == NONE` is incorrect as a general statement.
> 
> * In some cases the mask represents a grouping of unrelated things (e.g. the Flags field in Traceparent has bits for is_sampled and is_id_random). In those scenarios asking a question `mask == 0` has no semantic meaning imo.
> * But in other cases bitmasks are used as a quick check for set members, e.g. you have a group of callbacks / handlers for a given instrumentation point and you want to control via configuration which handlers are allowed in a given locus. In this scenario the question `mask == 0` makes total sense as you can short circuit the whole loop, and it is completely reasonable to write the question as `mask == NONE`.

I think the reasoning is that we have seen enough cases of a mistake described in the first bullet that we think it is OK to sacrifice the convenience you get for the second bullet's case.

**Closed** 2023-05-15 14:58 UTC
Labels: bug
